// Generated by CoffeeScript 1.6.3
(function() {
  var coffeeCmd, fs, path, watch;

  path = require('path');

  fs = require('fs');

  coffeeCmd = require('coffee-script/lib/coffee-script/command');

  exports.watch = watch = function() {
    var stdout;
    stdout = fs.createWriteStream('/dev/null');
    process.title = "cake-dog: " + (path.basename(process.cwd()));
    process.__defineGetter__('stdout', function() {
      return stdout;
    });
    process.__defineGetter__('stderr', function() {
      return stdout;
    });
    return coffeeCmd.run();
  };

  watch();

}).call(this);
