// Generated by CoffeeScript 1.8.0
(function() {
  var cakedog, commands, path;

  path = require('path');

  commands = require('./commands');

  cakedog = function(options) {
    var output, source, _options;
    if (options == null) {
      options = {};
    }
    output = options.output, source = options.source;
    _options = {
      output: path.resolve(output || 'lib'),
      source: path.resolve(source || 'src')
    };
    task('compile', "once compile coffee scripts to javascript files", function(options) {
      return commands.compile(_options);
    });
    task('watch', 'real-time compile coffee scripts to javascript files', function(options) {
      return commands.watch(_options, process.exit);
    });
    return task('unwatch', 'stop compile coffee scripts to javascript files', function(options) {
      return commands.unwatch(_options);
    });
  };

  module.exports = cakedog;

}).call(this);
