// Generated by CoffeeScript 1.7.1
(function() {
  var commands, path, _commonOptions;

  path = require('path');

  commands = require('./commands');

  _commonOptions = {
    output: path.resolve('lib'),
    source: path.resolve('src')
  };

  task('compile', "once compile coffee scripts to javascript files", function(options) {
    return commands.compile(_commonOptions);
  });

  task('compile:watch', 'real-time compile coffee scripts to javascript files', function(options) {
    return commands.watch(_commonOptions);
  });

  task('compile:unwatch', 'stop compile coffee scripts to javascript files', function(options) {
    return commands.unwatch(_commonOptions);
  });

}).call(this);
