// Generated by CoffeeScript 1.6.3
(function() {
  var coffeeCmd, fs, path, watch;

  path = require('path');

  fs = require('fs');

  coffeeCmd = require('coffee-script/lib/coffee-script/command');

  exports.watch = watch = function() {
    var args, i, src, _ref;
    process.title = "cake-dog: " + (path.basename(process.cwd()));
    src = null;
    _ref = process.argv;
    for (i in _ref) {
      args = _ref[i];
      if (args === '-c') {
        src = process.argv[Number(i) + 1];
        break;
      }
    }
    return fs.exists(src, function(exists) {
      var stdout;
      if (!exists) {
        fs.mkdirSync(src);
      }
      if (process.argv[2] === 'quiet') {
        stdout = fs.createWriteStream('/dev/null');
        process.__defineGetter__('stdout', function() {
          return stdout;
        });
        process.__defineGetter__('stderr', function() {
          return stdout;
        });
        process.argv.splice(2, 1);
      }
      return coffeeCmd.run();
    });
  };

  watch();

}).call(this);
