// Generated by CoffeeScript 1.6.3
(function() {
  var coffeeCmd, fs, path, watch;

  path = require('path');

  fs = require('fs');

  coffeeCmd = require('coffee-script/lib/coffee-script/command');

  exports.watch = watch = function() {
    var stdout;
    process.title = "cake-dog: " + (path.basename(process.cwd()));
    if (process.argv[2] === 'quiet') {
      stdout = fs.createWriteStream('/dev/null');
      process.__defineGetter__('stdout', function() {
        return stdout;
      });
      process.__defineGetter__('stderr', function() {
        return stdout;
      });
      process.argv.splice(2, 1);
    }
    return coffeeCmd.run();
  };

  watch();

}).call(this);
