// Generated by CoffeeScript 1.7.1
(function() {
  var cli, commander, pkg;

  commander = require('commander');

  pkg = require('../package.json');

  cli = function() {};

  module.exports = cli;

}).call(this);
