// Generated by CoffeeScript 1.7.1
(function() {
  var cli, commander, commands, pkg, _;

  commander = require('commander');

  _ = require('lodash');

  pkg = require('../package.json');

  commands = require('./commands');

  cli = function() {
    commander.version(pkg.version).usage('[options] <command>').option('-o, --output <output>', 'set the output directory for compiled JavaScript').option('-s, --source <source>', 'set the source directory for CoffeeScript');
    commander.command('compile').description('compile to JavaScript and save as .js files').action(function() {
      return commands.compile(_.last(arguments).parent);
    });
    commander.command('watch').description('watch for the file changes and compile to .js files').action(function() {
      return commands.watch(_.last(arguments).parent);
    });
    commander.command('unwatch').description('stop watch for the file changes').action(function() {
      return commands.unwatch(_.last(arguments).parent);
    });
    commander.command('resurrect').description('resurrect previously watched processes').action(function() {
      return commands.unwatch(_.last(arguments).parent);
    });
    return commander.parse(process.argv);
  };

  module.exports = cli;

}).call(this);
