// Generated by CoffeeScript 1.7.1
(function() {
  var Notifier, coffee, coffeeCmd, colors, fork, fs, notifier, path;

  path = require('path');

  fs = require('fs');

  colors = require('colors');

  coffeeCmd = require('coffee-script/lib/coffee-script/command');

  coffee = require('coffee-script');

  Notifier = require('node-notifier');

  notifier = new Notifier;

  fork = function() {
    var stdout;
    process.title = "cake-dog: " + (path.basename(process.cwd()));
    coffee.on('failure', function(err) {
      return notifier.notify({
        title: 'Compile Error!',
        message: err.toString()
      });
    });
    stdout = fs.createWriteStream('/dev/null');
    process.__defineGetter__('stdout', function() {
      return stdout;
    });
    process.__defineGetter__('stderr', function() {
      return stdout;
    });
    return coffeeCmd.run();
  };

  fork();

}).call(this);
