// Generated by CoffeeScript 1.6.3
(function() {
  var callback, colors, dogFile, exec, spawn;

  exec = require('child_process').exec;

  spawn = require('child_process').spawn;

  colors = require('colors');

  dogFile = "" + __dirname + "/../bin/dog";

  callback = function(err, stdout, stderr) {
    if (err != null) {
      console.log(err.toString().red);
      console.log('Message:'.grey);
      console.log(stdout.toString().red);
    } else {
      console.log(stdout.toString().green);
    }
    return process.exit();
  };

  task('watch', 'real-time compile coffee scripts to javascript files', function(options) {
    var watch;
    return watch = exec("" + dogFile + " watch", {
      timeout: 100
    }, callback);
  });

  task('stop', 'stop compile coffee scripts to javascript files', function(options) {
    return exec("" + dogFile + " stop", callback);
  });

  task('generate', "once compile coffee scripts to javascript files", function(options) {
    return exec("" + dogFile + " generate", callback);
  });

}).call(this);
