// Generated by CoffeeScript 1.6.3
(function() {
  var callback, colors, dogFile, exec;

  exec = require('child_process').exec;

  colors = require('colors');

  dogFile = "" + __dirname + "/../bin/dog";

  callback = function(err, stdout, stderr) {
    if ((err != null) || stderr.length > 0) {
      if (stderr.length > 0) {
        console.log(stderr.toString().trim().red);
      }
      console.log('Message:'.grey);
      console.log(stdout.toString().trim().red);
    } else {
      console.log(stdout.toString().trim().green);
    }
    return process.exit();
  };

  task('compile', "once compile coffee scripts to javascript files", function(options) {
    return exec("" + dogFile + " compile", callback);
  });

  task('compile:watch', 'real-time compile coffee scripts to javascript files', function(options) {
    return exec("" + dogFile + " compile_watch", {
      timeout: 100
    }, callback);
  });

  task('compile:unwatch', 'stop compile coffee scripts to javascript files', function(options) {
    return exec("" + dogFile + " compile_unwatch", callback);
  });

}).call(this);
